# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcc-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install cmake ninja-build gcc-10
          cmake --version
          ninja --version
          g++-10 --version
          
      - name: g++ release unit tests
        uses: HorstBaerbel/action-ctest@1.0
        with:
          sourcedir: '.'
          builddir: 'build_gcc_release'
          cmakeoptions: '--config Release -G Ninja -DCMAKE_CXX_COMPILER=g++-10 -DBUILD_DOC=OFF'
          ctestoptions: ''
          
  clang-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install cmake ninja-build clang-11
          cmake --version
          ninja --version
          clang++-11 --version
      - uses: actions/checkout@v2
      - name: clang release unit tests
        uses: HorstBaerbel/action-ctest@1.0
        with:
          sourcedir: '.'
          builddir: 'build_clang_release'
          cmakeoptions: '--config Release -G Ninja -DCMAKE_CXX_COMPILER=clang++-11 -DBUILD_DOC=OFF'
          ctestoptions: ''
    
  clang-with-sanitizers:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install cmake ninja-build clang-11
          cmake --version
          ninja --version
          clang++-11 --version
      - uses: actions/checkout@v2
      - name: clang debug with sanitizers
        uses: HorstBaerbel/action-ctest@1.0
        with:
          sourcedir: '.'
          builddir: 'build_clang_debug'
          cmakeoptions: '--config Debug -G Ninja -DCMAKE_CXX_COMPILER=clang++-11 -DBUILD_DOC=OFF -DECM_ENABLE_SANITIZERS="address;leak;undefined"'
          ctestoptions: ''
  
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
